# Generated by Django 4.2.5 on 2024-10-13 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_userevent_start_notified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('not_started', 'Не приступал'), ('in_progress', 'В работе'), ('completed', 'Выполнено')], default='not_started', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserEventStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.userevent')),
            ],
            options={
                'unique_together': {('user_event', 'user')},
            },
        ),
        migrations.AddField(
            model_name='userevent',
            name='statuses',
            field=models.ManyToManyField(through='events.UserEventStatus', to='events.status'),
        ),
    ]
