# Generated by Django 4.2.5 on 2024-10-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_status_usereventstatus_userevent_statuses'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usereventstatus',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usereventstatus',
            name='status',
        ),
        migrations.RemoveField(
            model_name='usereventstatus',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usereventstatus',
            name='user_event',
        ),
        migrations.RemoveField(
            model_name='userevent',
            name='statuses',
        ),
        migrations.AddField(
            model_name='userevent',
            name='last_notification_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userevent',
            name='notification_frequency',
            field=models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно'), ('never', 'Никогда')], default='never', max_length=20),
        ),
        migrations.AddField(
            model_name='userevent',
            name='notification_type',
            field=models.CharField(choices=[('periodic', 'Периодическое'), ('specific', 'Точное время')], default='periodic', max_length=20),
        ),
        migrations.AddField(
            model_name='userevent',
            name='specific_notification_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.DeleteModel(
            name='UserEventStatus',
        ),
    ]
