# Generated by Django 4.2.5 on 2024-10-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_userevent_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userevent',
            old_name='last_notification_time',
            new_name='last_notification_sent_at',
        ),
        migrations.RemoveField(
            model_name='userevent',
            name='notification_frequency',
        ),
        migrations.RemoveField(
            model_name='userevent',
            name='notification_type',
        ),
        migrations.RemoveField(
            model_name='userevent',
            name='specific_notification_time',
        ),
        migrations.AddField(
            model_name='userevent',
            name='notification_frequency_days',
            field=models.PositiveIntegerField(default=0, help_text='Частота уведомлений в днях (0 — без повторов)'),
        ),
    ]
