# Generated by Django 4.2.5 on 2024-10-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_rename_last_notification_time_userevent_last_notification_sent_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userevent',
            old_name='last_notification_sent_at',
            new_name='last_notified_at',
        ),
        migrations.RemoveField(
            model_name='userevent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userevent',
            name='notification_frequency_days',
        ),
        migrations.AddField(
            model_name='userevent',
            name='notification_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('none', 'None')], default='none', max_length=10),
        ),
    ]
