# Generated by Django 4.2.5 on 2024-11-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_rename_last_notification_sent_at_userevent_last_notified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='notification_frequency',
            field=models.CharField(choices=[('minutely', 'Minutely'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('none', 'None')], default='none', max_length=10),
        ),
    ]
