# Generated by Django 4.2.5 on 2024-12-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_userevent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='next_notification_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
