# Generated by Django 4.2.5 on 2024-12-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_userevent_next_notification_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='next_notification_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
