# Generated by Django 4.2.5 on 2024-12-04 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_alter_userevent_next_notification_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='notification_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('none', 'None')], default='none', max_length=10),
        ),
    ]
