# Generated by Django 4.2.5 on 2024-12-04 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_userevent_notification_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userevent',
            name='last_notified_at',
        ),
    ]
