# Generated by Django 4.2.5 on 2025-03-23 11:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scientific_publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scientificpublication',
            name='id_for_unique_identify_component',
            field=models.CharField(default=uuid.uuid4, max_length=50, unique=True, verbose_name='Уникальный идентификатор'),
        ),
    ]
