# Generated by Django 4.2.5 on 2025-01-27 16:09

from django.db import migrations, models
import django_quill.fields
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('short_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ConferenceAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название конференции')),
                ('description', models.TextField(verbose_name='Описание')),
                ('start_date', models.DateField(verbose_name='Начальная дата проведения')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Конечная дата проведения')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время проведения')),
                ('organizer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Организатор')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Контактный email')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Контактный телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('preview_image', imagekit.models.fields.ProcessedImageField(upload_to='conference_images/%Y/%m/%d', verbose_name='Превью изображение')),
                ('preview_image_description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Краткое описание фотографии')),
                ('content', django_quill.fields.QuillField(default='', verbose_name='Содержание статьи')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Скрыть объявление')),
            ],
            options={
                'verbose_name': 'Объявление о конференции',
                'verbose_name_plural': 'Объявления о конференциях',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='Заголовок')),
                ('short_description', models.TextField(max_length=280, verbose_name='Краткое описание')),
                ('post_type', models.CharField(choices=[('NEWS', 'News'), ('ANNOUNCEMENT', 'Announcement')], default='NEWS', max_length=12, verbose_name='Тип поста')),
                ('preview_image', imagekit.models.fields.ProcessedImageField(upload_to='photos/%Y/%m/%d', verbose_name='Превью фото')),
                ('preview_image_description', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Краткое описание фотографии')),
                ('content', django_quill.fields.QuillField(verbose_name='Содержание статьи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('display', models.BooleanField(default=True, verbose_name='Отображать?')),
            ],
            options={
                'verbose_name': 'пост',
                'verbose_name_plural': 'посты',
            },
        ),
    ]
