# Generated by Django 4.2.5 on 2025-01-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preview_image_description',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Краткое описание фотографии'),
        ),
    ]
