# Generated by Django 4.2.5 on 2024-11-20 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0018_alter_post_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название конференции')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('time', models.TimeField(verbose_name='Время проведения')),
                ('location', models.CharField(max_length=200, verbose_name='Место проведения')),
                ('organizer', models.CharField(max_length=100, verbose_name='Организатор')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Контактный email')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Контактный телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Объявление о конференции',
                'verbose_name_plural': 'Объявления о конференциях',
            },
        ),
    ]
