# Generated by Django 4.2.5 on 2024-12-04 17:02

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_remove_conferenceannouncement_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferenceannouncement',
            name='preview_image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='conference_images/%Y/%m/%d', verbose_name='Превью изображение'),
        ),
        migrations.AlterField(
            model_name='conferenceannouncement',
            name='start_date',
            field=models.DateField(verbose_name='Начальная дата проведения'),
        ),
    ]
