# Generated by Django 4.2.5 on 2024-11-28 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_conferenceannouncement'),
        ('news', '0020_alter_post_post_type'),
    ]

    operations = [
    ]
