# Generated by Django 4.2.5 on 2024-12-10 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_conferenceannouncement'),
        ('news', '0020_alter_post_post_type'),
    ]

    operations = [
    ]
