# Generated by Django 4.2.5 on 2024-12-11 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_alter_conferenceannouncement_preview_image_and_more'),
        ('news', '0021_merge_20241128_1757'),
    ]

    operations = [
    ]
