# Generated by Django 4.2.5 on 2024-12-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_alter_conferenceannouncement_preview_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenceannouncement',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Скрыть объявление'),
        ),
    ]
