# Generated by Django 4.2.5 on 2024-12-21 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_conferenceannouncement_is_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferenceannouncement',
            name='author',
        ),
        migrations.RemoveField(
            model_name='conferenceannouncement',
            name='updated_at',
        ),
    ]
