# Generated by Django 4.2.5 on 2024-12-20 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0014_alter_teacher_subjects'),
        ('guidance', '0003_alter_student_admission_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postgraduate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postgraduate_entries', to='guidance.student', verbose_name='Аспирант')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postgraduate_entries', to='employee.teacher', verbose_name='Руководитель')),
            ],
            options={
                'verbose_name': 'Запись аспирантуры',
                'verbose_name_plural': 'Записи аспирантуры',
            },
        ),
    ]
