# Generated by Django 4.2.5 on 2024-12-27 13:17

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EditablePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название страницы (для отображения в админ-панели)')),
                ('text', mdeditor.fields.MDTextField(blank=True, verbose_name='Контент Markdown')),
                ('page', models.SlugField(max_length=100, unique=True, verbose_name='Идентификатор страницы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'редактируемая страница',
                'verbose_name_plural': 'редактируемые страницы',
            },
        ),
    ]
