# Generated by Django 4.2.5 on 2024-12-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editable_pages', '0010_tag_scientificpublication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scientificpublication',
            options={'verbose_name': 'Научная публикация', 'verbose_name_plural': 'Научные публикации'},
        ),
        migrations.AddField(
            model_name='scientificpublication',
            name='id_for_unique_identify_component',
            field=models.CharField(default='default_id', max_length=50, unique=True, verbose_name='Уникальный идентификатор'),
        ),
        migrations.AddField(
            model_name='scientificpublication',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ISBN'),
        ),
        migrations.AddField(
            model_name='scientificpublication',
            name='pages',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Страницы'),
        ),
        migrations.AddField(
            model_name='scientificpublication',
            name='vol_n',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Том и номер'),
        ),
        migrations.AlterField(
            model_name='scientificpublication',
            name='author',
            field=models.JSONField(verbose_name='Авторы'),
        ),
        migrations.AlterField(
            model_name='scientificpublication',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='scientificpublication',
            name='file',
            field=models.TextField(blank=True, null=True, verbose_name='PDF файл (base64)'),
        ),
        migrations.AlterField(
            model_name='scientificpublication',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название публикации'),
        ),
        migrations.AlterField(
            model_name='scientificpublication',
            name='source',
            field=models.CharField(max_length=200, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='scientificpublication',
            name='tags',
            field=models.ManyToManyField(to='editable_pages.tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='scientificpublication',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='scientificpublication',
            name='year',
            field=models.IntegerField(verbose_name='Год'),
        ),
    ]
