# Generated by Django 4.2.5 on 2025-06-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcing_data_from_excel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputForParcingModuleGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.CharField(max_length=255)),
                ('discipline', models.CharField(max_length=255)),
                ('group_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'output_for_parcing_module_grade',
            },
        ),
    ]
