# Generated by Django 4.2.5 on 2025-06-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcing_data_from_excel', '0002_outputforparcingmodulegrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='outputforparcingmodulegrade',
            name='id_teachers_in_discipline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
