# Generated by Django 4.2.5 on 2025-06-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcing_data_from_excel', '0003_outputforparcingmodulegrade_id_teachers_in_discipline'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurlCommandsDummy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Curl Commands',
                'verbose_name_plural': 'Curl Commands',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FileUploadsDummy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'File Uploads',
                'verbose_name_plural': 'File Uploads',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OutputFilesDummy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Output Excel Files',
                'verbose_name_plural': 'Output Excel Files',
                'managed': False,
            },
        ),
    ]
