# Generated by Django 4.2.5 on 2025-01-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование дисциплины')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание дисциплины')),
            ],
            options={
                'verbose_name': 'учебная дисциплина',
                'verbose_name_plural': 'учебные дисциплины',
            },
        ),
    ]
