# Generated by Django 4.2.5 on 2024-12-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_year',
            field=models.PositiveIntegerField(default=2024, verbose_name='Год поступления'),
            preserve_default=False,
        ),
    ]
