# Generated by Django 4.2.5 on 2025-01-27 16:09

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpersEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', imagekit.models.fields.ProcessedImageField(blank=True, default=None, null=True, upload_to='avatars/%Y/%m/%d')),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True)),
                ('position', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'персонал',
                'verbose_name_plural': 'учебно-вспомогательный персонал',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', imagekit.models.fields.ProcessedImageField(blank=True, default=None, null=True, upload_to='avatars/%Y/%m/%d')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='Почта')),
                ('messenger', models.CharField(blank=True, max_length=50, null=True, verbose_name='Мессенджер')),
                ('degree', models.CharField(blank=True, choices=[('DOCTOR_TECH', 'Доктор технических наук'), ('CANDIDATE_TECH', 'Кандидат технических наук'), ('CANDIDATE_PED', 'Кандидат педагогических наук'), ('DOCTOR_PHYS_MATH', 'Доктор физико-математических наук'), ('CANDIDATE_PHYS_MATH', 'Кандидат физико-математических наук'), ('DOCTOR_ECONOM', 'Доктор экономических наук'), ('CANDIDATE_ECONOM', 'Кандидат экономических наук')], max_length=100, null=True, verbose_name='Степень')),
                ('rank', models.CharField(blank=True, choices=[('READER', 'Доцент'), ('PROFESSOR', 'Профессор')], max_length=100, null=True, verbose_name='Звание')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('experience', models.IntegerField(blank=True, null=True, verbose_name='Общий стаж работы (в годах)')),
                ('professional_experience', models.IntegerField(blank=True, null=True, verbose_name='Стаж работы по специальности (в годах)')),
                ('education', models.TextField(blank=True, null=True, verbose_name='Образование')),
                ('qualification', models.TextField(blank=True, null=True, verbose_name='Повышение квалификации')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Биография')),
                ('subjects', models.ManyToManyField(related_name='subjects', to='subject.subject', verbose_name='Дисциплины')),
            ],
            options={
                'verbose_name': 'преподаватель',
                'verbose_name_plural': 'преподаватели',
            },
        ),
    ]
