# Generated by Django 4.2.5 on 2025-03-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='exam_schedule_graduation',
            field=models.URLField(blank=True, null=True, verbose_name='Расписание экзаменов (выпускные курсы)'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='exam_schedule_non_graduation',
            field=models.URLField(blank=True, null=True, verbose_name='Расписание экзаменов (невыпускные курсы)'),
        ),
    ]
