# Generated by Django 4.2.5 on 2025-01-27 16:09

import department.employee.schedule.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_file_name', models.CharField(blank=True, default='-', editable=False, max_length=256, null=True, verbose_name='Название импортированного файла')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='employee.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
        migrations.CreateModel(
            name='ScheduleLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_time', models.IntegerField(choices=[(1, '8:30 - 10:10'), (2, '10:20 - 12:00'), (3, '12:20 - 14:00'), (4, '14:10 - 15:50'), (5, '16:00 - 17:40'), (6, '18:00 - 19:30'), (7, '19:40 - 21:10'), (8, '21:20 - 22:50')], verbose_name='Время пары')),
                ('week_number', models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота')], verbose_name='День недели')),
                ('group', models.CharField(max_length=128, verbose_name='Группы')),
                ('name', models.CharField(max_length=256, verbose_name='Название предмета')),
                ('type', models.CharField(help_text='Семинар, лекция, лабораторные занятия либо пользовательский тип', max_length=128, verbose_name='Тип пары')),
                ('cabinet', models.CharField(blank=True, max_length=128, null=True, verbose_name='Кабинет')),
                ('subgroup', models.CharField(blank=True, max_length=128, null=True, verbose_name='Подгруппа')),
                ('schedule', models.ForeignKey(help_text='Пара обязательно должна быть привязана к объекту расписания. Если нет объекта с нужным преподавателем, создайте нажал на зелёный плюс. Для одного преподавателя доступно только одно расписание', on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='schedule.schedule', verbose_name='Расписание')),
            ],
            options={
                'verbose_name': 'Пара',
                'verbose_name_plural': 'Пары',
            },
        ),
        migrations.CreateModel(
            name='ScheduleLessonDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.CharField(max_length=5, validators=[department.employee.schedule.models.validate_lesson_date_format], verbose_name='Дата начала')),
                ('end_date', models.CharField(blank=True, max_length=5, null=True, validators=[department.employee.schedule.models.validate_lesson_date_format], verbose_name='Дата конца (опционально)')),
                ('alternatively_period', models.BooleanField(default=False, help_text='Да - через неделю. Нет - каждая неделя', verbose_name='Через неделю?')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='schedule.schedulelesson')),
            ],
            options={
                'verbose_name': 'Дата пары',
                'verbose_name_plural': 'Даты пар',
            },
        ),
    ]
