# Generated by Django 4.2.5 on 2025-04-24 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_teacher_exam_schedule_graduation_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='teacher',
            field=models.OneToOneField(blank=True, help_text='Преподаватель, связанный с данным пользователем', null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.teacher', verbose_name='Связанный преподаватель'),
        ),
    ]
