# Generated by Django 4.2.5 on 2025-01-27 16:09

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('content', django_quill.fields.QuillField(verbose_name='Содержание')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='photos/%Y/%m/%d', verbose_name='Превью фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to='employee.teacher', verbose_name='Привязан к')),
            ],
            options={
                'verbose_name': 'достижение',
                'verbose_name_plural': 'достижения',
            },
        ),
    ]
